// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqqgu3xcX8oLIu6xCrgUfRMs_gZNFfhUs',
    appId: '1:505357991164:web:0dc5ad11db0e8cca306b79',
    messagingSenderId: '505357991164',
    projectId: 'splashapp-2bc1d',
    authDomain: 'splashapp-2bc1d.firebaseapp.com',
    storageBucket: 'splashapp-2bc1d.firebasestorage.app',
    measurementId: 'G-FBJ45QBHDY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqkRP8wgaZ5Z47z1RP3422pB1pZp_8O5Y',
    appId: '1:505357991164:android:8ff1f7d739fb9c10306b79',
    messagingSenderId: '505357991164',
    projectId: 'splashapp-2bc1d',
    storageBucket: 'splashapp-2bc1d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGjwUE-LP80T7H2iW12PPZwxs66XGOmls',
    appId: '1:505357991164:ios:aecb6db3d9f305ba306b79',
    messagingSenderId: '505357991164',
    projectId: 'splashapp-2bc1d',
    storageBucket: 'splashapp-2bc1d.firebasestorage.app',
    iosBundleId: 'com.example.splashapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGjwUE-LP80T7H2iW12PPZwxs66XGOmls',
    appId: '1:505357991164:ios:aecb6db3d9f305ba306b79',
    messagingSenderId: '505357991164',
    projectId: 'splashapp-2bc1d',
    storageBucket: 'splashapp-2bc1d.firebasestorage.app',
    iosBundleId: 'com.example.splashapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqqgu3xcX8oLIu6xCrgUfRMs_gZNFfhUs',
    appId: '1:505357991164:web:f3dc319e2392bb97306b79',
    messagingSenderId: '505357991164',
    projectId: 'splashapp-2bc1d',
    authDomain: 'splashapp-2bc1d.firebaseapp.com',
    storageBucket: 'splashapp-2bc1d.firebasestorage.app',
    measurementId: 'G-W6N7CH2BXR',
  );
}
